name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v5.1.0
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8
        pylint
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
